name: Android Debug Build and Upload

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  build_debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
 
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          # If your project structure requires local.properties in a specific subdirectory (e.g., android/),
          # adjust the path accordingly:
          # echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: app/build/outputs/apk
